### ISSUE TITLE
0.2.11 release?

### ISSUE THREAD

**Issue by matthiasbeyer** [rust-lang-nursery/glob#48]
I'd like to see another release here, as there are a few fixes:

* 8e5cfd6
* d685089
* 0745a7e

Which are not yet in crates.io.

Please release `0.2.11` if you think the current version is stable enough.

**Comment by matthiasbeyer** [comment]
Follow-up(-Question): Why don't you `git tag` your releases?

**Comment by alexcrichton** [comment]
Sure! I just pushed 0.2.11

**Comment by matthiasbeyer** [comment]
:+1:
