### ISSUE TITLE
Tests fail to build on Windows

### ISSUE THREAD

**Issue by retep998** [rust-lang-nursery/glob#85]
```
   Compiling glob v0.3.0 (C:\crater\workdir)
error[E0432]: unresolved import `std::ffi::AsOsStr`
    --> src\lib.rs:1081:17
     |
1081 |             use std::ffi::AsOsStr;
     |                 ^^^^^^^^^^-------
     |                 |         |
     |                 |         help: a similar name exists in the module: `OsStr`
     |                 no `AsOsStr` in `ffi`

error[E0624]: method `prefix` is private
    --> src\lib.rs:1086:33
     |
1086 |                 .and_then(|p| p.prefix().map(|p| p.join("*")))
     |                                 ^^^^^^

error: aborting due to 2 previous errors
```

**Comment by KodrAus** [comment]
Oops... Thanks for the report @retep998!

I've reached out to see if we've got an Azure Pipelines plan we can use here in the nursery so we can check Windows in CI too.

**Comment by KodrAus** [comment]
Alrighty, we've got a Pipelines project created so I'll go set it up so we get CI for Windows running.

**Comment by KodrAus** [comment]
CI is now set up for Windows so if anybody would like to take a shot at getting these tests to compile on Windows they should be checked properly now going forward.

**Comment by SOF3** [comment]
What is that `prefix` function even supposed to do? It isn't anywhere in the documentation of `PathBuf` or `Path`.

**Comment by SOF3** [comment]
What is that `prefix` function even supposed to do?

The one in the Rust source code has a `prefix() -> Prefix` definition, but `Prefix` does not contain `join` either.
